# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133k21bjbEhsHx-XEgPTr1XcwDnqOAqKJ
"""

# Load in pickle and model
import pickle
with open("healthy_meals_pipeline.pkl", "wb") as f:
    pickle.dump(pipeline, f)

import pandas as pd
import gradio as gr

import gzip
with gzip.open("healthy_meals_pipeline.pkl.gz", "rb") as f:
    pipeline = pickle.load(f)


# Build Gradio app
def predict(
    total_sessions,
    gross_session_length,
    active_days,
    active_quarters,
    avg_sessions_per_quarter,
    recency_days,
    age,
    tech_comfort_score,
    education,
    income_level,
    device_type
):
    row = pd.DataFrame([{
        "TOTAL_SESSIONS_2022": total_sessions,
        "GROSS_TOTAL_SESSION_LENGTH_2022": gross_session_length,
        "ACTIVE_DAYS_2022": active_days,
        "ACTIVE_QUARTERS_2022": active_quarters,
        "AVG_SESSIONS_PER_ACTIVE_QUARTER": avg_sessions_per_quarter,
        "RECENCY_DAYS": recency_days,
        "AGE": age,
        "TECH_COMFORT_SCORE": tech_comfort_score,
        "EDUCATION": education,
        "INCOME_LEVEL": income_level,
        "DEVICE_TYPE": device_type
    }])

    prob = pipeline.predict_proba(row)[0][1]
    risk = "Low" if prob >= 0.6 else "Medium" if prob >= 0.4 else "High"
    return f"Renewal Probability: {prob:.2f} | Churn Risk: {risk}"

# Set up Gradio interface
iface = gr.Interface(
    fn=predict,
    inputs=[
        gr.Number(label="Total Sessions 2022"),
        gr.Number(label="Gross Total Session Length 2022"),
        gr.Number(label="Active Days 2022"),
        gr.Number(label="Active Quarters 2022"),
        gr.Number(label="Avg Sessions per Active Quarter"),
        gr.Number(label="Recency Days"),
        gr.Number(label="Age"),
        gr.Number(label="Tech Comfort Score"),
        gr.Radio(["high school", "other", "graduate", "post graduate"], label="Education"),
        gr.Radio(["low", "medium", "high", "very high"], label="Income Level"),
        gr.Radio(["multi-device", "mobile-only", "desktop-only"], label="Device Type")
    ],
    outputs="text",
    title="Healthy Meals Renewal Predictor",
    description="Enter customer attributes to predict renewal probability."
)

iface.launch()
